// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApmVjrc37zjviuxzj8Z2-4_T7miOGv2R4',
    appId: '1:186376091883:web:2ab2816e5b90cabf4066ae',
    messagingSenderId: '186376091883',
    projectId: 'pma2026',
    authDomain: 'pma2026.firebaseapp.com',
    storageBucket: 'pma2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeQHmySUxWo1xuEIpatUyMj0g2_FcnW5c',
    appId: '1:186376091883:android:974e620ddad3b6454066ae',
    messagingSenderId: '186376091883',
    projectId: 'pma2026',
    storageBucket: 'pma2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv-ubwGx3yHnZqBIOzXpYvogWJrqI1hZk',
    appId: '1:186376091883:ios:ac448fead8a4a3bc4066ae',
    messagingSenderId: '186376091883',
    projectId: 'pma2026',
    storageBucket: 'pma2026.firebasestorage.app',
    iosBundleId: 'com.example.pma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv-ubwGx3yHnZqBIOzXpYvogWJrqI1hZk',
    appId: '1:186376091883:ios:ac448fead8a4a3bc4066ae',
    messagingSenderId: '186376091883',
    projectId: 'pma2026',
    storageBucket: 'pma2026.firebasestorage.app',
    iosBundleId: 'com.example.pma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApmVjrc37zjviuxzj8Z2-4_T7miOGv2R4',
    appId: '1:186376091883:web:f0fbe3e49a325b404066ae',
    messagingSenderId: '186376091883',
    projectId: 'pma2026',
    authDomain: 'pma2026.firebaseapp.com',
    storageBucket: 'pma2026.firebasestorage.app',
  );
}
